name: Build and test js2nix
on: [push]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: js2nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run build
        run: nix-build --no-out-link -j auto ./build.nix
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/13e0d337037b3f59eccbbdf3bc1fe7b1e55c93fd.tar.gz
      - uses: cachix/cachix-action@v12
        with:
          name: js2nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - name: Install Node.js & Yarn
        run: nix-env -i nodejs -i yarn -f '<nixpkgs>'
      - name: Install Node.js modules
        run: yarn install
      - name: Run tests
        run: yarn test
  integration-tests:
    needs: [build, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: js2nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run tests in nix develop
        run: nix develop -c jest
  lock-diff:
    needs: [build, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: js2nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Generate Nix expression from the yarn.lock file
        run: nix develop -c js2nix --lock ./yarn.lock --out ./yarn.lock.nix
      - name: Check git diff
        run: git diff --exit-code HEAD
